baseURL: http://rodneymaiato.art
languageCode: en-us
title: Rodney Maiato
enableEmoji: true
googleAnalytics: G-GZWZCLTZXH


params:
  author: Rodney Maiato
  description: Artist Rodney Maiato showcases his sketches and paintings that he creates in portable moleskine sketchbooks.

# menu config
menu:
  main:
    - name: About
      url: /about
      weight: 20
    - name: Posts
      url: /posts
      weight: 10

summaryLength: 12 

markup:
  goldmark:
    renderer:
      unsafe: true
