baseURL: http://rodneymaiatoart.netlify.app
languageCode: en-us
title: Rodney Maiato
enableEmoji: true

# menu config
menu:
  main:
    - name: About
      url: /about
      weight: 20

summaryLength: 20

markup:
  goldmark:
    renderer:
      unsafe: true
