baseURL: http://rodneymaiato.art
languageCode: en-us
title: Rodney Maiato 
enableEmoji: true

# menu config
menu:
  main:
  - name: Rodney Maiato 
    url: /
    weight: 10
  - name: Posts 
    url: /posts
    weight: 20
  - name: About
    url: /about
    weight: 30  
  - name: Contact
    url: /contact
    weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true