baseURL: http://rodneymaiato.art
languageCode: en-us
title: Rodney Maiato
enableEmoji: true

# menu config
menu:
  main:
    - name: Posts
      url: /posts
      weight: 10
    - name: Bio
      url: /bio
      weight: 20
    - name: Tags
      url: /tags
      weight: 30

markup:
  goldmark:
    renderer:
      unsafe: true
