baseURL: http://rodneymaiato.art
languageCode: en-us
title: Rodney Maiato
enableEmoji: true
googleAnalytics: G-GZWZCLTZXH

# menu config
menu:
  main:
    - name: About
      url: /about
      weight: 20
    - name: Posts
      url: /posts
      weight: 10

summaryLength: 12 

markup:
  goldmark:
    renderer:
      unsafe: true
